name: Papadam Studios
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5968364286236465
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#67008d'
    - '#ab71bf'
    - '#944bae'
    - '#dcc4e4'
  brandStrength: 0.9277583516668528
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
